.catalog:
  name: "CloudFlare DNS"
  version: "v0.7.9"
  description: "Rancher External DNS service powered by CloudFlare. Requires Rancher minimal version v1.6.13-rc1"
  minimum_rancher_version: v1.6.13-rc1
  questions:
    - variable: "CLOUDFLARE_KEY"
      label: "CloudFlare API key"
      description: "API key for your CloudFlare account"
      type: "string"
      required: true
    - variable: "CLOUDFLARE_EMAIL"
      label: "CloudFlare email address"
      description: "Email address associated with your CloudFlare account"
      type: "string"
      required: true
    - variable: "TTL"
      label: "TTL"
      description: "The resource record cache time to live (TTL), in seconds (minimum 30 / maximum 7200)"
      type: "int"
      default: 60
      min: 30
      max: 7200
      required: false
    - variable: "ROOT_DOMAIN"
      label: "Domain Name"
      description: "The domain name managed by CloudFlare."
      type: "string"
      required: true
    - variable: "NAME_TEMPLATE"
      label: "DNS Name Template"
      description: |
        Name template used to construct the subdomain part (left of the domain) of the DNS record names.
        Supported placeholders: %{{service_name}}, %{{stack_name}}, %{{environment_name}}.
        By default DNS entries will be named '<service>.<stack>.<environment>.<domain>'.
      type: "string"
      default: "%{{service_name}}.%{{stack_name}}.%{{environment_name}}"
      required: false
    - variable: "HEALTH_CHECK"
      label: "Health Check Interval"
      description: |
        The health check interval for this service, in milliseconds.
        Raise this value if the global requests for your account are exceeding the CloudFlare API rate limits.
      type: "int"
      min: 2000
      max: 60000
      default: 5000
      required: true

cloudflare:
  health_check:
    port: 1000
    interval: ${HEALTH_CHECK}
    unhealthy_threshold: 2
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 8000
